# Use Node.js image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json tailwind.config.js jsconfig.json ./

# Copy the rest of the app
#COPY ./src ./app/src

COPY . .

RUN npm install


# Build the React app
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
